// Staff sign-in. A plain HTML form (no client JavaScript needed): it POSTs to
// /api/admin/login, which checks the email + password, sets the httpOnly session
// cookie and redirects to /admin. Accounts are created by `pnpm db:seed`
// (SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD), see src/server/db/seed.ts.

// PageProps<"/admin/login"> is generated by `next typegen`. In Next.js 16,
// searchParams is a Promise, so the page is async and awaits it.
export default async function AdminLoginPage(props: PageProps<"/admin/login">) {
  const { error } = await props.searchParams;
  const field = "rounded border border-zinc-300 p-2";

  return (
    <main className="mx-auto max-w-sm p-6">
      <h1 className="mb-4 text-xl font-semibold text-zinc-900">Staff sign in</h1>
      <form method="post" action="/api/admin/login" className="grid gap-3">
        <label htmlFor="email" className="text-sm font-medium text-zinc-700">
          Email
        </label>
        <input
          id="email"
          name="email"
          type="email"
          required
          autoComplete="username"
          data-testid="admin-email-input"
          className={field}
        />
        <label htmlFor="password" className="text-sm font-medium text-zinc-700">
          Password
        </label>
        <input
          id="password"
          name="password"
          type="password"
          required
          autoComplete="current-password"
          data-testid="admin-password-input"
          className={field}
        />
        {error === "1" && (
          <p role="alert" className="text-sm text-red-700" data-testid="error-message">
            Wrong email or password.
          </p>
        )}
        <button
          type="submit"
          data-testid="admin-login-button"
          className="rounded bg-teal-700 p-2 text-white"
        >
          Sign in
        </button>
      </form>
    </main>
  );
}
