// Staff sign-in. A plain HTML form (no client JavaScript needed): it POSTs to
// /api/admin/login, which sets the httpOnly cookie and redirects to /admin.

// PageProps<"/admin/login"> is generated by `next typegen`. In Next.js 16,
// searchParams is a Promise, so the page is async and awaits it.
export default async function AdminLoginPage(props: PageProps<"/admin/login">) {
  const { error } = await props.searchParams;

  return (
    <main className="mx-auto max-w-sm p-6">
      <h1 className="mb-4 text-xl font-semibold text-zinc-900">Staff sign in</h1>
      <form method="post" action="/api/admin/login" className="grid gap-3">
        <label htmlFor="token" className="text-sm font-medium text-zinc-700">
          Staff access token
        </label>
        <input
          id="token"
          name="token"
          type="password"
          required
          autoComplete="current-password"
          data-testid="admin-token-input"
          className="rounded border border-zinc-300 p-2"
        />
        {error === "1" && (
          <p role="alert" className="text-sm text-red-700" data-testid="error-message">
            That token is not correct.
          </p>
        )}
        <button
          type="submit"
          data-testid="admin-login-button"
          className="rounded bg-teal-700 p-2 text-white"
        >
          Sign in
        </button>
      </form>
    </main>
  );
}
