// Staff sign-in. A plain HTML form (no client JavaScript needed): it POSTs to
// /api/admin/login, which checks the email + password, sets the httpOnly session
// cookie and redirects to /admin. Accounts are created by `pnpm db:seed`
// (SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD), see src/server/db/seed.ts.
//
// This page is a SERVER component that renders shadcn components. Most of them
// (Card, Input, Button) are plain styled elements; Label is a client component
// (Radix), and a server component may render client components freely.

import { CircleAlert, ShieldCheck } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

// PageProps<"/admin/login"> is generated by `next typegen`. In Next.js 16,
// searchParams is a Promise, so the page is async and awaits it.
export default async function AdminLoginPage(props: PageProps<"/admin/login">) {
  const { error } = await props.searchParams;

  return (
    <main className="flex flex-1 items-center justify-center bg-muted/40 p-6">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <ShieldCheck className="mb-1 size-6 text-primary" aria-hidden />
          <CardTitle className="text-lg">Staff sign in</CardTitle>
          <CardDescription>Use the account your clinic admin created for you.</CardDescription>
        </CardHeader>
        <CardContent>
          <form method="post" action="/api/admin/login" className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                name="email"
                type="email"
                required
                autoComplete="username"
                data-testid="admin-email-input"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                name="password"
                type="password"
                required
                autoComplete="current-password"
                data-testid="admin-password-input"
              />
            </div>
            {error === "1" && (
              <Alert variant="destructive" data-testid="error-message">
                <CircleAlert />
                <AlertDescription>Wrong email or password.</AlertDescription>
              </Alert>
            )}
            <Button type="submit" size="lg" data-testid="admin-login-button">
              Sign in
            </Button>
          </form>
        </CardContent>
      </Card>
    </main>
  );
}
